name: Build and Deploy on PR Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    environment: prd
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract short SHA
        id: vars
        run: echo "short_sha=$(echo '${{ github.sha }}' | cut -c1-6)" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.IMAGE_NAME }}:latest
            ${{ vars.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Trigger Deploy Hook
        env:
          DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
          DEPLOY_HOOK_TOKEN: ${{ secrets.DEPLOY_HOOK_TOKEN }}
          SHORT_SHA: ${{ needs.build.outputs.short_sha }}
          FOLDER_NAME: ${{ vars.FOLDER_NAME }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
        run: |
          curl --fail --connect-timeout 10 --max-time 120 \
            -X POST "$DEPLOY_HOOK_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DEPLOY_HOOK_TOKEN" \
            -d "{\"folder\":\"${FOLDER_NAME}\",\"service\":\"${SERVICE_NAME}\",\"image\":\"${IMAGE_NAME}:${SHORT_SHA}\"}"
