name: Build and Deploy on PR Merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup git user
        run: |
          git config --global user.name "dalmow"
          git config --global user.email "kelvi.dalmazo@gmail.com"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short SHA and create tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          git tag $SHORT_SHA
          git push origin $SHORT_SHA

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sdalm:latest
            ${{ secrets.DOCKER_USERNAME }}/sdalm:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger deploy
        env:
          DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
        run: |
          curl --fail "$DEPLOY_HOOK_URL"
